### PR TITLE
Fix armv8l typo and add it to arm64 case instead of armhf

### PR DESCRIPTION
**Pull request by benthetechguy**

### CODE REVIEW

**Comment by Dmole** [comment]
Squash it please.

**Comment by benthetechguy** [comment]
Done. When I made the original commits I had no access to git so I was using the GitHub website's editor that only lets you edit one file per commit.

**Comment by Dmole** [comment]
https://en.m.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores

There are 32b only, and 64b only v8, maybe we should check 

    getconf LONG_BIT

To be sure

**Comment by Dmole** [comment]
https://github.com/llvm/llvm-project/blob/main/lldb/include/lldb/Utility/ArchSpec.h

Is a bit crazy.

**Comment by benthetechguy** [comment]
Oh boy, that's a lot of different types. Yeah, it would be a good idea to add `getconf LONG_BIT` to test if it's capable of executing 64-bit instructions. I'll add that in when I get back to my PC.

**Comment by benthetechguy** [comment]
OK, I added the logic to make it go to the correct arch whether it supports 32 or 64 bits. I also added support for 32 bit x86 as I noticed it was missing.

**Comment by Dmole** [comment]
It will need a

    apt-get -qq install getconf

if armv8l is detected as it's not installed by default.

**Comment by benthetechguy** [comment]
Done

**Pull request merged**
